//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp3.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class user24Entities : DbContext
    {
        public user24Entities()
            : base("name=user24Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Auth> Auth { get; set; }
        public virtual DbSet<Divisions> Divisions { get; set; }
        public virtual DbSet<Docs> Docs { get; set; }
        public virtual DbSet<InfoClient> InfoClient { get; set; }
        public virtual DbSet<InfoPropusk> InfoPropusk { get; set; }
        public virtual DbSet<Obshii> Obshii { get; set; }
        public virtual DbSet<Organization> Organization { get; set; }
        public virtual DbSet<ReceivingParty> ReceivingParty { get; set; }
        public virtual DbSet<Sotrudnik> Sotrudnik { get; set; }
        public virtual DbSet<Visiting> Visiting { get; set; }
    }
}
